# Generated by Django 3.2.5 on 2021-07-10 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('short_name', models.CharField(max_length=100, verbose_name='Короткое Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('version', models.CharField(max_length=100, unique=True, verbose_name='Версия')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата начала действия справочника этой версии')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Код элемента')),
                ('value', models.CharField(max_length=100, verbose_name='Значение элемента')),
                ('handbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.handbook', verbose_name='Справочник')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочника',
            },
        ),
    ]
