# Generated by Django 3.2.5 on 2021-07-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbook',
            name='uid',
            field=models.IntegerField(default=0, verbose_name='Идентификатор'),
        ),
    ]
